// Datos públicos del portal Alumno: no contiene nombres ni teléfonos.
const ASSIGNMENTS = [
  {code:'PNL-01-K7A',studentNo:1,case:1,title:'Mensaje escolar: separar, limpiar y normalizar',topic:'Tokenización + Stop Words + Normalización',data:{text:'Mañana entregaremos el proyecto de PNL en el salón de computación.',stop:['el','de','en','del','la'],variants:['entregaremos','entregamos','entregado']}},
  {code:'PNL-02-M4Q',studentNo:2,case:2,title:'Buscador: ¿qué aviso se parece más a la pregunta?',topic:'BoW + TF-IDF + Similitud Coseno',data:{query:'¿Cuándo entrego el proyecto de inteligencia artificial?',docs:['Entrega del proyecto de inteligencia artificial el viernes.','Horario del laboratorio de programación.','Lista de materiales para la práctica de redes.']}},
  {code:'PNL-03-R8C',studentNo:3,case:3,title:'Boletín escolar: elegir la herramienta adecuada',topic:'Markov + TextRank + LDA + CNN/RNN + LLM',data:{items:['resumir una nota larga','agrupar noticias por tema','generar una continuación de texto','detectar un patrón local en una frase','trabajar con contexto amplio y conversar']}},
  {code:'PNL-04-T2L',studentNo:4,case:1,title:'Aviso de laboratorio: limpiar antes de comparar',topic:'Tokenización + Stop Words + Normalización',data:{text:'Los alumnos trabajarán con datos y modelos de lenguaje natural.',stop:['los','con','y','de'],variants:['trabajarán','trabajando','trabajó']}},
  {code:'PNL-05-V9D',studentNo:5,case:2,title:'Preguntas frecuentes del curso',topic:'BoW + TF-IDF + Similitud Coseno',data:{query:'¿Dónde realizaremos la práctica de PNL?',docs:['La práctica de PNL será en el centro de cómputo.','La tarea se entrega el miércoles.','El examen incluye conceptos de algoritmos.']}},
  {code:'PNL-06-H5N',studentNo:6,case:3,title:'Noticias del plantel: detectar el tipo de tarea',topic:'Markov + TextRank + LDA + CNN/RNN + LLM',data:{items:['resumir tres párrafos','separar noticias por tema','predecir la siguiente palabra','reconocer un patrón corto','responder preguntas con contexto']}},
  {code:'PNL-07-J3P',studentNo:7,case:1,title:'Invitación: ¿qué palabras ayudan y cuáles distraen?',topic:'Tokenización + Stop Words + Normalización',data:{text:'Hoy el grupo está invitado a la temática de participación en equipo para el quince de septiembre.',stop:['el','está','a','la','de','en','para'],variants:['participación','participando','participó']}},
  {code:'PNL-08-X6B',studentNo:8,case:2,title:'Buscador de recursos',topic:'BoW + TF-IDF + Similitud Coseno',data:{query:'¿Qué material necesito para la práctica de inteligencia artificial?',docs:['Material para la práctica de inteligencia artificial: libreta y equipo.','Calendario de exposiciones del grupo.','Normas del centro de cómputo.']}},
  {code:'PNL-09-F1W',studentNo:9,case:3,title:'Ayudante escolar: seleccionar método',topic:'Markov + TextRank + LDA + CNN/RNN + LLM',data:{items:['encontrar palabras clave para un resumen','descubrir grupos de temas','continuar una oración','detectar una señal local','mantener una conversación con contexto']}},
  {code:'PNL-10-S8E',studentNo:10,case:1,title:'Reporte: de texto humano a datos',topic:'Tokenización + Stop Words + Normalización',data:{text:'El procesamiento del lenguaje convierte palabras en representaciones que una computadora puede manejar.',stop:['el','del','en','que','una'],variants:['convierte','convirtiendo','convirtió']}},
  {code:'PNL-11-Q5Z',studentNo:11,case:2,title:'Clasificar una pregunta escolar',topic:'BoW + TF-IDF + Similitud Coseno',data:{query:'¿Cuál documento habla de modelos de lenguaje?',docs:['Modelos de lenguaje y procesamiento de texto.','Fechas de exámenes parciales.','Material de laboratorio de electrónica.']}},
  {code:'PNL-12-N7U',studentNo:12,case:3,title:'Analizar textos de un mural escolar',topic:'Markov + TextRank + LDA + CNN/RNN + LLM',data:{items:['crear un resumen breve','encontrar temas repetidos','predecir una palabra siguiente','reconocer una expresión local','explicar y generar texto con contexto']}},
  {code:'PNL-13-C4Y',studentNo:13,case:1,title:'Mensaje de proyecto: tokenizar antes de decidir',topic:'Tokenización + Stop Words + Normalización',data:{text:'Nuestro equipo presentará un ejemplo de inteligencia artificial aplicada a textos.',stop:['nuestro','un','de','a'],variants:['presentará','presentando','presentó']}},
  {code:'PNL-14-P9G',studentNo:14,case:2,title:'Comparar respuestas del laboratorio',topic:'BoW + TF-IDF + Similitud Coseno',data:{query:'¿Qué técnica asigna más peso a una palabra rara pero importante?',docs:['TF-IDF ayuda a destacar términos importantes.','La tokenización divide el texto.','Los embeddings representan significado en vectores.']}},
  {code:'PNL-15-L2K',studentNo:15,case:3,title:'Sistema escolar: muchos métodos, un problema',topic:'Markov + TextRank + LDA + CNN/RNN + LLM',data:{items:['resumir automáticamente','descubrir temas','generar una secuencia','reconocer patrones de frases','usar información contextual amplia']}},
  {code:'PNL-16-D8R',studentNo:16,case:1,title:'Aviso de actividad: limpiar y después contar',topic:'Tokenización + Stop Words + Normalización',data:{text:'La actividad de PNL requiere identificar palabras, quitar ruido y reconocer formas de una misma palabra.',stop:['la','de','y','una'],variants:['identificar','identificando','identificó']}},
  {code:'PNL-17-W5M',studentNo:17,case:2,title:'Encontrar el texto más cercano',topic:'BoW + TF-IDF + Similitud Coseno',data:{query:'¿Qué significa similitud entre dos textos?',docs:['La similitud coseno compara la orientación de dos vectores.','Stop Words elimina palabras muy comunes.','LDA busca temas dentro de documentos.']}},
  {code:'PNL-18-B3T',studentNo:18,case:3,title:'Biblioteca digital: escoger tecnología',topic:'Markov + TextRank + LDA + CNN/RNN + LLM',data:{items:['sacar las ideas principales','separar documentos por temas','modelar el siguiente paso de una secuencia','detectar patrones locales en texto','trabajar con relaciones amplias entre palabras']}},
  {code:'PNL-19-G6V',studentNo:19,case:1,title:'Reflexión: ¿cómo pasa el texto a un modelo?',topic:'Tokenización + Stop Words + Normalización',data:{text:'Primero se analiza el texto, después se transforma y finalmente se modela para obtener una respuesta.',stop:['se','el','después','y','para','una'],variants:['transforma','transformando','transformó']}},
  {code:'PNL-20-Y1H',studentNo:20,case:2,title:'Recomendador escolar: medir relación',topic:'BoW + TF-IDF + Similitud Coseno',data:{query:'¿Qué representación usa números para comparar textos?',docs:['BoW cuenta apariciones de palabras.','TF-IDF pondera la importancia de las palabras.','Los embeddings representan relaciones semánticas como vectores.']}}
];


const TEAMS = [
  {team:1,title:'Tokenización: ¿cómo cortamos el lenguaje?',members:[1,2,3,4,5],guide:'Explicar palabra, carácter y subpalabra; mostrar un ejemplo sencillo; decir una ventaja y una dificultad de cada forma.'},
  {team:2,title:'Stemming vs. lematización: dos formas de normalizar',members:[6,7,8,9,10],guide:'Explicar qué significa reducir palabras; comparar fuerza bruta contra análisis del contexto; usar al menos tres palabras de ejemplo.'},
  {team:3,title:'BoW y TF-IDF: contar no es lo mismo que medir importancia',members:[11,12,13,14,15],guide:'Explicar BoW; después explicar TF, IDF y por qué una palabra común puede perder peso.'},
  {team:4,title:'Similitud coseno y embeddings: comparar significado',members:[16,17,18,19,20],guide:'Explicar vectores con un dibujo; comparar similitud coseno; explicar con palabras sencillas qué aporta un embedding.'}
];


const STUDENTS=ASSIGNMENTS.map(a=>({n:a.studentNo,code:a.code,team:TEAMS.find(t=>t.members.includes(a.studentNo))?.team}));
window.PNL_DATA={STUDENTS,ASSIGNMENTS,TEAMS};
